global: bank
basic: BasicAccount.cpp
		g++ BasicAccount.cpp -o basic
savings: SavingsAccount.cpp BasicAccount.cpp
		g++ SavingsAccount.cpp BasicAccount.cpp -o savings
bank: bank.cpp BasicAccount.cpp SavingsAccount.cpp
