global: curved swappointervalues primes swapvalues swappointers swapreferences addlargenumbers
curved: curved.cpp
primes: primes.cpp
swappointervalues: swappointervalues.cpp
swappointers: swappointers.cpp
swapvalues: swapvalues.cpp
swapreferences: swapreferences.cpp
addlargenumbers: addlargenumbers.cpp
