global: task1 driver dictionary
task1: task1.cpp
singlylinked: singlylinked.cpp
doublylinked: doublylinked.cpp
driver: driver.cpp singlylinked.cpp doublylinked.cpp
dictionary: dictionary.cpp singlylinked.cpp

clean:
	rm driver task1 dictionary
